### ISSUE TITLE
Set additional properties on array items

### ISSUE THREAD

**Issue by TomasBahnik** [losisin/helm-values-schema-json#103]
When I specify `-noAdditionalProperties true`  and `assetLinks: [] # @schema item: object` schema correctly generates

```
  "assetLinks": {
      "items": {
          "additionalProperties": false,
          "type": "object"
      },
      "type": "array"
  }
```

But there is no way to set `"additionalProperties": true,` like  `assetLinks: [] # @schema item: object;item: additionalProperties: true` to get

```
    "assetLinks": {
        "items": {
            "additionalProperties": true,
            "type": "object"
        },
        "type": "array"
    }
```

**Comment by losisin** [comment]
@TomasBahnik I think you have extra `item:` in your yaml comment. this yaml:
```yaml
assetLinks: [] # @schema item: object ; additionalProperties: true
```
generates this schema:
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "assetLinks": {
            "additionalProperties": true,
            "items": {
                "type": "object"
            },
            "type": "array"
        }
    },
    "type": "object"
}
```
btw, leaving out `additionalProperties` or setting it to true has the effect because `true` is implied or default

**Comment by losisin** [comment]
ah, you probably mean adding `additionalProperties` under `items`.

**Comment by losisin** [comment]
you can try this:
```yaml
assetLinks:
  - {} # @schema additionalProperties: true
```
and then the schema will be:
```json
"assetLinks": {
    "items": {
        "additionalProperties": true,
        "properties": {},
        "type": "object"
    },
    "type": "array"
}
```
at this point, either this or leave it out

**Comment by TomasBahnik** [comment]
Thank you, that's OK.
