### ISSUE TITLE
patternProperties not working properly (?)

### ISSUE THREAD

**Issue by geothechr** [losisin/helm-values-schema-json#108]
Hello everyone,
I am using the helm values schema plugin, in order to autogenerate values.schema.json file.

My values configuration (which is passed as input to helm schema plugin), is the following:
```
rootconfig: # @schema required:true;type:object
  instances: # @schema patternProperties: {"^.*$": {"type": "object"}};minProperties:1
    "dummyInstance": # @schema required:true;type:object
      name: "dummy01"
      enabled: false
      ....
```

What I would like to achieve:
- I want `dummyInstance` key to serve as a **placeholder/wildcard**, so that for any key name (instead of it) the same rules would apply.

The current configuration does not work - if I add any other instance name, instead of `dummyInstance`, rules defined in annotations do not apply. Moreover, I see the following configuration, in the autogenerated `values.schema.json`:
```
        "rootconfig": {
            "properties": {
                "instances": {
                    "minProperties": 1,
                    "patternProperties": {
                        "^.*$": {
                            "type": "object"
                        }
                    },
                    "properties": {
                        "dummyInstance": {
                            "properties": {
```

As far I understand, the last **properties** part should not contain the name "dummyInstance". I even tested the values.schema.json without the properties part, and it worked correctly.

Any ideas?:)

**Comment by losisin** [comment]
@geothechr there is no way at this moment to skip key from generating json schema. you might want to try some of the meta properties like `default`, but they only make sense if you build some kind of interface from the generated schema. some users of this plugin use it like that
