### ISSUE TITLE
required fields

### ISSUE THREAD

**Issue by curuvija** [losisin/helm-values-schema-json#21]
Hi,

Thanks for this nice plugin. We started using it the other day for our internal Helm charts. Do you have any plans to implement required fields somehow like from comments/annotations or any other way?

Thanks,
Milos

**Comment by losisin** [comment]
if there is interest I would support it

**Comment by curuvija** [comment]
Thanks for quick reply. I can assist you to the degree if you need help.

**Comment by losisin** [comment]
@curuvija required keyword is now available in main branch. see here: https://github.com/losisin/helm-values-schema-json/tree/main/docs#required

Thanks for the feedback!

**Comment by curuvija** [comment]
@losisin thanks a lot :)
