### ISSUE TITLE
Allow adding additionalProperties: false to the generated Schema

### ISSUE THREAD

**Issue by hajowieland** [losisin/helm-values-schema-json#38]
Currently the generated JSON Schema does not take into account when values are set which are not defined a values.yaml.

In JSON schema, we can set `additionalProperties: false` to properties (see [Documentation](https://json-schema.org/understanding-json-schema/reference/object#additional-properties)), which then causes e.g. `helm lint` to error when there are values set which are for example incorrectly indented.

This helps debugging wrongly indented values, which can be hard to spot or even cause other side effects like removing resources via gitOps (when pruning is enabled) if values are just missing some spaces.

Example:

values.yaml:
```yaml
onevalue:
  secondvalue:
    test: 123
```

With the currently generated JSON Schema, the following option values would not cause any errors:

values-test.yaml:
```yaml
onevalue:
  test: 123
```

Generated schema:
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "onevalue": {
            "properties": {
                "secondvalue": {
                    "properties": {
                        "test": {
                            "type": "integer"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "type": "object"
}
```

Running `helm lint`:
```
helm lint --strict . -f values-test.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

But when `additionalProperties: false` is added to all properties in the JSON schema like this:

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "onevalue": {
            "additionalProperties": false,
            "properties": {
                "secondvalue": {
                    "additionalProperties": false,
                    "properties": {
                        "test": {
                            "type": "integer"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "type": "object"
}
```

then running `helm lint` fails:

```
helm lint --strict . -f values-test.yaml
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - onevalue: Additional property test is not allowed

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
test:
- onevalue: Additional property test is not allowed


Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by losisin** [comment]
@hajowieland thank you for the suggestion and pull request. I agree that **additionaProperties** would be useful to add. However, I'm not entirely sure having it as cli flag is best approach as it's a but strict. Maybe having it parsed from comment will provide more flexibility to our users. In addition to that, we can set the parent object to false from flag or hardcode to handle the case for root yaml nodes. What do think?

**Comment by hajowieland** [comment]
> @hajowieland thank you for the suggestion and pull request. I agree that **additionaProperties** would be useful to add. However, I'm not entirely sure having it as cli flag is best approach as it's a bit strict. Maybe having it parsed from comment will provide more flexibility to our users. In addition to that, we can set the parent object to false from flag or hardcode to handle the case for root yaml nodes. What do think?

Thanks for your reply and your great work for this project!
I was thinking about the use case where a users wants to easily set **additionaProperties: false** to all properties in the schema - hence the CLI flag. This would not break usage for existing users, as the CLI flag would need to be explicitly set.

> "Maybe having it parsed from comment will provide more flexibility to our users. In addition to that, we can set the parent object to false from flag or hardcode to handle the case for root yaml nodes."

Can you explain or show an example how that would look like if a users would like to set the additionaProperties comment for all properties?

**Comment by losisin** [comment]
this is how to do it from parsing comments: https://github.com/losisin/helm-values-schema-json/pull/37/files
we still need to agree for how to solve it for the parent object. `additionaProperties` as cli flag kind of breaks character from all other fields

**Comment by RothAndrew** [comment]
Given the latest change with `-schemaRoot.id`, `-schemaRoot.title`, and `schemaRoot.description` flags, it makes sense to add a `-schemaRoot.additionalProperties` flag.

**Comment by losisin** [comment]
> Given the latest change with `-schemaRoot.id`, `-schemaRoot.title`, and `schemaRoot.description` flags, it makes sense to add a `-schemaRoot.additionalProperties` flag.

Already did it earlier today but haven't written any tests yet. Once that's done I'll release new version

**Comment by losisin** [comment]
@hajowieland @RothAndrew new features are available in v1.4.0

**Comment by nickexported** [comment]
Hi! Do I understand correctly, that it only applies to the root? So it will look smth like this 
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
"additionalProperties": false,   
 "properties": {
        "affinity": {
            
            "properties": {},
            "type": "object"
        }
  }
``` ?


As far as I understand than for following schema:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "affinity": {
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "type": "object"
    }
  }
}
```  
this input will be valid:

```json
{"affinity":{"smth":"abc"}}
```

However if schema will look as following:


```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "affinity": {
      "additionalProperties": false,
      "properties": {
        "logGroupId": {
          "type": "string"
        }
      },
      "type": "object"
    }
  }
}
```
than that input won't be valid as expected. Maybe make this flag applied to all nested objects? Say in schema.go in parseNode func in case block `case yaml.MappingNode: ... `

**Comment by losisin** [comment]
@nickexported `-schemaRoot.additionalProperties` applies only to the root object of the schema. For yaml nodes you should use line comment as usual `# @schema additionalProperties: false`
