### ISSUE TITLE
Support for declaring items types in empty array

### ISSUE THREAD

**Issue by ryan-dyer-sp** [losisin/helm-values-schema-json#48]
I dont seem to be able to figure out how properly declare that items within an array have a type unless my array object in values.yaml has an array with those objects declared.  But I want the default to be [].

For example:
```
domains: [] 
# - domain.com
# - domain.co
``` 
results in `domain: { type: array }`  
I want to be able to make this become `domain: { type: array, items: { type: string }}`

**Comment by losisin** [comment]
@ryan-dyer-sp I've added support to set Items type from comment. you can use it like this:

```yaml
imagePullSecrets: [] # @schema item: object
```

which will generate json schema:

```json
"imagePullSecrets": {
    "items": {
        "type": "object"
    },
    "type": "array"
},
```

You need to update plugin version to 1.2.2
