### ISSUE TITLE
Add support for patternProperties

### ISSUE THREAD

**Issue by Jonasei** [losisin/helm-values-schema-json#56]
Support for [patternProperties](https://json-schema.org/understanding-json-schema/reference/object#patternProperties) would be really useful if added.

The case I am trying to solve is to get something like this, where I know the property is an object with key-values, and the values should all be strings:

```json
"environmentVariables": {
	"type": "object",
	"patternProperties": {
		"^.*": {
			"type": "string"
		}
	}
}
```

Cheers!

**Comment by losisin** [comment]
`patternProperties` is now available in v1.2.4 and here is how to use it: https://github.com/losisin/helm-values-schema-json/blob/main/testdata/full.yaml#L42.

**Comment by losisin** [comment]
@Jonasei P.S. thanks for the previous contribution :)

**Comment by Jonasei** [comment]
Great! Thanks for the quick response 👍
