### ISSUE TITLE
feat: support formatting options for the generated schema

### ISSUE THREAD

**Issue by hegerdes** [losisin/helm-values-schema-json#61]
This tool is super helpful, but currently it conflicts with other pre-commit hooks I have.

The generated json schema uses 4 spaces for indention, the common `pretty-format-json` hook formats for 2 spaces. So each time files get modified.  
The same goes for `end-of-file-fixer`. The generated json does not have a final new line character - resulting in modified files by two hooks every time.

Is it possible to add the final new-line by default and support custom output formatting options like `indent`?

**Comment by losisin** [comment]
@hegerdes thanks for the feedback and great suggestions. I can make `-indent` option that takes even number and 4 being default. New line will be added by default to keep the generated schema POSIX compliant. I'll let you know when it will be available

**Comment by hegerdes** [comment]
Awesome! 

and super quick reply.  
As a workaround: I currently have the generated json schemas in my exclude list for `end-of-file-fixer` and `pretty-format-json`

**Comment by losisin** [comment]
@hegerdes requested features are available in v1.3.0. don't forget to update your hooks
