### ISSUE TITLE
Add `$id`, `title`, and `description` top level keys

### ISSUE THREAD

**Issue by RothAndrew** [losisin/helm-values-schema-json#64]
AFAIK the tool doesn't currently offer the ability to set `$id`, `title`, and `description` entries to the top level object. This results in `undefined` entries when using tools such as Adobe's [jsonschema2md](https://github.com/adobe/jsonschema2md) tool.

Example:

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/d07dc7e9-c33f-4bf0-9e7f-d315d19b2739)

If `$id`, `title`, and `description` fields were able to be added, I could get something like:

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/3f8f61af-ccfd-47a3-9b96-8db4400e8aa0)

Proposed Solution:

What about something like looking for a `@schemaroot` comment?:

```yaml
# @schemaroot $id: values.yaml; title: values.yaml; description: Helm chart values
```

More examples:
Without top level $id, title, description
![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/66065848-b865-4fe0-a820-8748a58ed2b4)

With top level $id, title, description
![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/af1eb5ba-dcec-4221-a895-3b0a206d42b3)

**Comment by RothAndrew** [comment]
My workaround for this was to do my own pre-commit hook, adding a `jq` command at the end.

In .pre-commit-config.yaml:
```yaml
  - repo: local
    hooks:
      - id: helm-schema
        name: helm-schema
        entry: scripts/helm-schema.sh
        language: script
        files: chart/values.yaml
        types: [yaml]
```

In scripts/helm-schema.sh:

```shell
#!/usr/bin/env sh

set -e

if ! helm plugin list | grep -q "schema"; then
  echo "Error: Helm plugin 'schema' is not installed. Please install helm-values-schema-json plugin! https://github.com/losisin/helm-values-schema-json#install" >&2
  exit 1
fi

helm schema -input chart/values.yaml -output chart/values.schema.json.tmp -draft 7 -indent 2
jq '. + {"$id": "values.yaml", "title": "values.yaml", "description": "Helm chart values."}' chart/values.schema.json.tmp > chart/values.schema.json
rm chart/values.schema.json.tmp
```

**Comment by losisin** [comment]
@RothAndrew adding `$id`, `title` and `description` to the root object sounds like a good idea. I would prefer to do it with CLI flags and eventually add feature to read settings from config file. Would that work for you?

**Comment by RothAndrew** [comment]
Sounds good!
