### ISSUE TITLE
`default: null` doesn't work

### ISSUE THREAD

**Issue by RothAndrew** [losisin/helm-values-schema-json#67]
If I use:

```
foo: null # @schema type: [string, null]; default: null
```

The default is not recorded in the schema.

I can use `default: "null"` which does work, but it makes it look like the default should be the string `"null"` rather than `null` which is not a string in YAML-land.

This issue looks to be unique to `null`. If I have a boolean like:

```
foo: true # @schema type: [boolean]; default: true
```

That works fine, and correctly says the default is `true`, not `"true"`

**Comment by losisin** [comment]
@RothAndrew  Is the issue how you declare it in comment or generated schema? I think it boils down to the yaml library because `null` and absent will be translated in go to `nil`.  If I remove that check, then every property will get `"Default: null` to the schema even if you don't use it comment. 
Can you provide more info or use case?

**Comment by RothAndrew** [comment]
EDIT: nevermind, skip to the bottom. Even if this tool did what I thought I wanted it to do, the `jsonschema2md` tool just discards the default key if its value is `null`.

---

Hello!

My use case is that I'm using this tool, followed by Adobe's `jsonschema2md` to do my documentation. It suits my needs better than helm-docs.

Several of my helm values default to `null`. If I do this in the values.yaml:

```yaml
someValue: null # @schema type: [string, null]; default: null
```

The default never shows up in the .schema.json file. 

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/90eac4a9-b228-4e5f-ae7e-7e9125bb1be5)

If I do this instead:

```yaml
someValue: null # @schema type: [string, null]; default: "null"
```

the .schema.json value has a default, but it is the string "null" instead of JSON's `null`.

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/6b46c5b0-dbb5-4be6-9748-a87fa3ff30ee)

My markdown documentation then makes it seem like the default value is the string "null"

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/ff067511-c655-401f-9068-294dd97b3760)

If I manually edit the .schema.json file to:

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/9ef7a3b5-7c70-478b-abf9-1cf39c7616cc)

...the default doesn't show up in the markdown at all... Maybe this is a limitation of JSON schema.. Okay nevermind, I'll figure out how to document this in a different way.

![image](https://github.com/losisin/helm-values-schema-json/assets/16000938/31139e5c-06bd-4227-8178-7d323c26fb76)
