### ISSUE TITLE
Consider adding hidden tag

### ISSUE THREAD

**Issue by nickexported** [losisin/helm-values-schema-json#73]
Sometimes you want to hide some fields not with readonly, but completly so external user won't have full schema.
What do you think about adding `# @schema hidden: true`? So it will ignore this field.

**Comment by gioppoluca** [comment]
+1 on this.
The use case for us is that we generate the form using the schema-json but there are some values that we do not want to expose to the user (for various reasons).
Having a "hidden" concept could allow to NOT generate the field, in this case I would propose an "exclude: true".

**Comment by gioppoluca** [comment]
the advantage is the we can use the single original values.yaml without having to have a values-redacted.yaml one

**Comment by losisin** [comment]
yeah, sure. sounds like a reasonable request and there is obviously interest for it. I'll try to find time for it this week but don't quote me on that :)
