### ISSUE TITLE
setting additionalProperties recursive

### ISSUE THREAD

**Issue by MrFreezeDZ** [losisin/helm-values-schema-json#95]
When running the schema-executable, the additionalProperties: false is not set for all properties. The only way I saw to set this is by the parameter `-schemaRoot.additionalProperties false`. This sets it only on the root properties. Is there any way to be able to let the schema-executable set additionalProperties: false for all nested properties without setting an annotation on each property?

**Comment by MrFreezeDZ** [comment]
I looked over the PR, and the discussion here https://github.com/losisin/helm-values-schema-json/issues/38. 
In my case this strictness would be exactly what I am looking for. This would even prevent typos when setting values. So a values.schema.json which contains additionalProperties=false recursive on every object would be a nice feature for me. 
In the case of an umbrella-helm-chart where the umbrella-chart has multiple dependencies and the author of the umbrella-chart does not maintain the dependencies it would be a nice feature to create the values.schema.json with additonalProperties=false on every object. This would make sure that key changes in one sub values.yaml could be identified automatically.

**Comment by pascal-hofmann** [comment]
Hi,
first of all: Thanks for this awesome tool!

I agree with @MrFreezeDZ and think there should be an option to enable `additionalProperties=false` for all objects. It is required to get a very strict schema, but it's very tedious to add it to every object manually via comment.

@losisin Would you accept a PR that adds this feature?

Cheers
Pascal

**Comment by losisin** [comment]
@MrFreezeDZ thanks for the feedback and the suggestion. Sounds reasonable to me and obviously there is interest for that. 
@pascal-hofmann pull request would be more than welcome and very much appreciated. I'm thinking command line flag like in the original PR `noAdditionalProperties` which would change default behaviour from `true` to `false`.  For backwards compatibility, `schemaRoot.additionalProperties` and annotation in yaml should take precedence and overwrite the default behaviour whichever it may be. Don't forget tests and updating documentation accordingly and we'll be good to go :)
